channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
# - snakemake=5.15.0
 - python=3.8.2
 - star=2.7.3a
 - fastqc=0.11.9
 - multiqc=1.8
 - trimmomatic=0.39
 - bbmap=38.79
 - subread=2.0.0
 - samtools=1.9
 - trinity=2.9.1
# - cufflinks=2.2.1=py36_2
 - blast=2.5.0
 - hmmer=3.3
 - transdecoder=5.5.0
 - pfam_scan=1.6
 - uniprot=1.3
 - trinotate=3.2.0
 - sqlite=3.30.1
 - bedtools=2.29.2
 - biopython=1.76
 - fastqc=0.11.9
 - bam2fastx=1.3.0
 - minimap2=2.17
 - samtools=1.9
 - cramtools=3.0.b47
 - bwa=0.7.17
 - requests=2.23.0
 - htslib=1.9
 - pathlib2=2.3.5
 - pyyaml=5.3.1
 - scipy=1.4.1
 - theano=1.0.4
 - hmmer2=2.3.2
 - six=1.14.0
 - perl=5.26.2
 - canu=2.0
 - bedops=2.4.39


#notes = cufflink version is too old, conflicting with the new version of python and snakemake, I did module load cufflink.. 

